### PR TITLE
Add quotes to operator.yaml

### PR DESCRIPTION
**Pull request by rhrazdil**
Templates that contain {{ }} without quotation cannot be further processed
with yq.

**What this PR does / why we need it**:

**Special notes for your reviewer**:
Related to https://github.com/kubevirt/cluster-network-addons-operator/pull/520
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
Would you please fix all the templates while at it?

**Comment by rhrazdil** [comment]
Yes, will do

**Comment by qinqon** [comment]
Can we check how it looks at CNAO to use sed instead of yq ?

**Comment by rhrazdil** [comment]
@qinqon Please take a look https://github.com/kubevirt/cluster-network-addons-operator/pull/536

**Pull request closed without merging**
