### PR TITLE
WIP: Use varlink to communicate with a nmstate running as a daemon

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold
We are facing EOF and also the nmstate logs does not appear even if we are printing them.

**Comment by qinqon** [comment]
There are issues at nmstate varlink server
```
437a177b81 started
2020-12-16 13:11:00,467 root         DEBUG    Async action: Delete profile: id:brext, uuid:186f3a97-c328-45f5-9eb9-15437a177b81 finished
----------------------------------------
Exception happened during processing of request from 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/varlink/server.py", line 327, in handle
    for reply in self.service.handle(message, _server=self.server, _request=self.request):
  File "/usr/lib/python3.6/site-packages/varlink/server.py", line 232, in handle
    for out in handle:
  File "/usr/lib/python3.6/site-packages/varlink/server.py", line 176, in _handle
    out = func(*(parameters[k] for k in method.in_type.fields.keys()), **kwargs)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstate_varlink.py", line 212, in Apply
    return {"log": get_logs(string_io)}
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstate_varlink.py", line 71, in get_logs
    log_list.append(json.loads(log))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 61 (char 60)
----------------------------------------
2020-12-16 13:11:03,705 root         WARNING  libnm version 1.26.2 mismatches NetworkManager version 1.22.8
2020-12-16 13:11:08,842 root         WARNING  libnm version 1.26.2 mismatches NetworkManager version 1.22.8
2020-12-16 13:11:13,951 root         WARNING  libnm version 1.26.2 mismatches NetworkManager version 1.22.8
2020-12-16 13:11:19,057 root         WARNING  libnm version 1.26.2 mismatches NetworkManager version 1.22.8
2020-12-16 13:11:24,146 root         WARNING  libnm version 1.26.2 mismatches NetworkManager version 1.22.8
2020-12-16 1
```

**Comment by cathay4t** [comment]
The log failure will be fixed by https://github.com/nmstate/nmstate/pull/1443

**Comment by qinqon** [comment]
Thanks @cathay4t can you backport it to 0.3?

**Comment by qinqon** [comment]
At default bridge test after node restart nmstatectl show is failing with 

```
{"level":"error","ts":1608205139.187068,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"","reconcilerKind":"Node","controller":"node","name":"node02","namespace":"","error":"error at node reconcile creating NodeNetworkState: error running nmstatectl show: failed connecting to varlink to call nmstate show: failed connecting to nmstate varlink server: timed out waiting for the condition, dial unix /varlink/nmstate.so: connect: connection refused"
```

**Comment by qinqon** [comment]
/hold
WIP

**Comment by qinqon** [comment]
Starting to look good, the last fix we need is to select the proper container at the failing test
```
 stderr 
./cluster/kubectl.sh exec -n nmstate nmstate-handler-lxm9q -- mv /usr/local/bin/vlan-filtering /usr/local/bin/vlan-filtering.bak
stdout: ...
, stderr Defaulting container name to nmstatectl.
Use 'kubectl describe pod/nmstate-handler-lxm9q -n nmstate' to see all of the containers in this pod.
```

**Pull request closed without merging**
