### PR TITLE
Add Radim as a maintainer

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:
Radim has being contributing a lot lately so is fair to make him
maintainer.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
/lgtm
/approve

Very well deserved. Radim's work on rollout touched most of the places of the project. His reviews caught bugs and assured clean patches. Last but not least, he proved to be able to navigate the project and fix its bugs.

**Comment by phoracek** [comment]
/override pull-kubernetes-nmstate-e2e-handler-k8s-future
/hold

FYI @rhrazdil

**Comment by rhrazdil** [comment]
Thank you!

/unhold

**Pull request merged**
