### PR TITLE
DNM: Run the e2e regression at mutiple nodes in parallel to check sta…

### PR DESCRIPTION
**Pull request by qinqon**
…bility

### CODE REVIEW

**Comment by qinqon** [comment]
About the vlan_filtering issue, looks like br1 is already there and nmstate fails, attached is the error with multiline fixed.
[error.log](https://github.com/nmstate/kubernetes-nmstate/files/3658269/error.log)

**Comment by qinqon** [comment]
ci test please

**Comment by qinqon** [comment]
Ther were a bug at bridgeDescription function, Instead of ReadInteval it was using ReadTimeout.

**Comment by phoracek** [comment]
@qinqon please cherry-pick https://github.com/nmstate/kubernetes-nmstate/pull/187 to this PR, I think it will solve the leftover bridge issue :)

**Comment by phoracek** [comment]
@qinqon tested with my PR on top https://github.com/nmstate/kubernetes-nmstate/pull/188, all lanes have passed

**Comment by phoracek** [comment]
@qinqon and I tested to enable the default bridged network test on top of my PR https://github.com/nmstate/kubernetes-nmstate/pull/189 and it is still raceful.

**Comment by qinqon** [comment]
Executions summary:

First pass:
- One job failure http://jenkins.ovirt.org/job/nmstate_kubernetes-nmstate_standard-check-pr/882//artifact/check-patch.k8s-1.14.6-4.el7.x86_64/mock_logs/script/stdout_stderr.log

**Comment by qinqon** [comment]
ci test please

**Pull request closed without merging**
