### PR TITLE
go.mod: update mongodb-driver to 1.11.2

### PR DESCRIPTION
**Pull request by dougsland**
Keep the mongodb-driver updated with the latest bits available. Improves the driver functionality, fixes and sec. patches.

Release note:
  ```release-note
  Update golang mongodb-driver to 1.11.2
  ```

### CODE REVIEW

**Comment by dougsland** [comment]
Closing this one as we only refer to mongodb in the go.mod/go.sum, looks like it's not used anymore. I will send a new one with `go mod tidy`

**Comment by dougsland** [comment]
@cybertron I believe it's good to update actually. Please let me know your thoughts.

```
$ kubernetes-nmstate> go mod graph  | grep -i mongo-driver
github.com/go-openapi/strfmt@v0.19.3 go.mongodb.org/mongo-driver@v1.0.3
github.com/go-openapi/validate@v0.19.5 go.mongodb.org/mongo-driver@v1.1.2
github.com/golang-migrate/migrate/v4@v4.6.2 go.mongodb.org/mongo-driver@v1.1.0
github.com/go-openapi/analysis@v0.19.5 go.mongodb.org/mongo-driver@v1.1.1
github.com/go-openapi/strfmt@v0.19.2 go.mongodb.org/mongo-driver@v1.0.3
```

```
$ kubernetes-nmstate> go mod graph  | grep -i go-openapi | more
github.com/nmstate/kubernetes-nmstate github.com/go-openapi/jsonpointer@v0.19.5
github.com/nmstate/kubernetes-nmstate github.com/go-openapi/jsonreference@v0.19.5
github.com/nmstate/kubernetes-nmstate github.com/go-openapi/swag@v0.19.14
```

**Comment by cybertron** [comment]
/ok-to-test
Looks fine to me assuming it passes ci.

**Comment by dougsland** [comment]
updated the patch to include the  `go mod vendor`

**Comment by dougsland** [comment]
oops nevermind :)

**Pull request merged**
