### PR TITLE
Bump kubevirtci

### PR DESCRIPTION
**Pull request by oshoval**
**Is this a BUG FIX or a FEATURE ?**:
/kind enhancement

**What this PR does / why we need it**:
Bump kubevirtci to consume a newer version

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by rhrazdil — COMMENTED** [review]
I don't see any reason not to update the tag.
Only the justification in the PR description is off - there is no reason to align with CNAO, as CNAO is unrelated to this project at this point. CNAO doesn't deploy knmstate anymore.

**Comment by oshoval** [comment]
> I don't see any reason not to update the tag. Only the justification in the PR description is off - there is no reason to align with CNAO, as CNAO is unrelated to this project at this point. CNAO doesn't deploy knmstate anymore.

Right thanks
updated

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1130/pull-kubernetes-nmstate-e2e-handler-k8s-future/1592077109033963520

not due to this PR right ? (i saw this lane really flaky in the past but not sure what is the current status and which tests are flaky)

**Comment by rhrazdil** [comment]
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1130/pull-kubernetes-nmstate-e2e-handler-k8s-future/1592077109033963520
> not due to this PR right ? (i saw this lane really flaky in the past but not sure what is the current status and which tests are flaky)

Yes, this is not related
/approve
/lgtm

**Comment by oshoval** [comment]
Thanks Radim

**Pull request merged**
