### PR TITLE
cluster-sync: Increase rollout timeout

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
In order to solve rollout timeouts during deploy,
increase the timeout.

**Special notes for your reviewer**:
Saw on both CI and locally

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by rhrazdil — APPROVED** [review]
Thanks!

/approve

**Comment by oshoval** [comment]
It isn't enough yet (assuming its transient as I saw locally)
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1052/pull-kubernetes-nmstate-e2e-handler-k8s-future/1519560280298754048

we might need to increase more

**Comment by qinqon** [comment]
Is not the rollout, we have to wait until the deployment/ds is created if it's not created rollout command will fail inmediatly

**Pull request merged**
