### PR TITLE
handler: Remove link unavailable w/a

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
There is a quite old NetworkManager 1.20 issue where link where not up [1], and k-nmstate do have a workaround for it. This change remove the workaround since it's quite old and possible not needed.

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove link unavailable workaround
```

### CODE REVIEW

**Comment by qinqon** [comment]
/retest 
```
===== 34bfee44934ac9f2b042a91f51e847088772839db58cd829935db6af7cb84c58 ====
Error response from daemon: cannot listen on the TCP port: listen tcp4 :43655: bind: address already in use
make: *** [Makefile:188: cluster-up] Error 1
```

**Comment by cybertron** [comment]
/lgtm

Assuming this passes ci.

**Pull request merged**
