### PR TITLE
Create 0.4.0 release

### PR DESCRIPTION
**Pull request by qinqon**
To run it at nmstate namespace

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by qinqon** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by phoracek** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by phoracek** [comment]
ci test please

**Pull request merged**
