### PR TITLE
Fix broken URL in comment

### PR DESCRIPTION
**Pull request by avishayt**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
There is a broken URL, this fixes it

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/lgtm
/approve

thanks !

**Comment by qinqon** [comment]
@avishayt can you fix DCO  with `git commit --amend -s`

**Comment by avishayt** [comment]
Sorry, forgot Signed-off-by, please LGTM again

**Pull request merged**
