### PR TITLE
[release-0.37] Decrease NNS refresh frequency and remove dyn attr

### PR DESCRIPTION
**Pull request by qinqon**
This is a cherry-pick from #682 

Depends-on: https://github.com/kubevirt/project-infra/pull/863

```release-note
Decrease NNS refresh frequency and remove dyn attr
```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold

Depends on https://github.com/kubevirt/project-infra/pull/863

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by qinqon** [comment]
/hold cancel
tests are in place

**Comment by phoracek** [comment]
/override pull-kubernetes-nmstate-docs-0.37

Unrelated Ruby dependency issue

**Pull request merged**
