### PR TITLE
Adapt automation to new logs dir

### LINKED ISSUE #1024: CI log artifacts seem incomplete
**What happened**:
It seems that after migration to ginkgo v2, the logs are not showing the part that begins and ends with failing spec.
Instead there is only full log.

Moreover though, the full log seems to be incomplete too, 
taking this run as an example:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1023/pull-kubernetes-nmstate-e2e-handler-k8s/1506625505825132544

we see ovs tests fail, but the log in [the artifacts ](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1023/pull-kubernetes-nmstate-e2e-handler-k8s/1506625505825132544/artifacts/kubernetes-nmstate.pod.logs)
doesn't contain it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- `NodeNetworkState` on affected nodes (use `kubectl get nodenetworkstate <node_name> -o yaml`):
- Problematic `NodeNetworkConfigurationPolicy`:
- kubernetes-nmstate image (use `kubectl get pods --all-namespaces -l app=kubernetes-nmstate -o jsonpath='{.items[0].spec.containers[0].image}'`):
- NetworkManager version (use `nmcli --version`)
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Others:

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:
After the migratin to ginkgo v2 the k8s reporter is creating a directory
per failing test, the automation scripts where not adapted to it.

**Special notes for your reviewer**:
Closes #1024 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold
Contains a commit to force to fail.

**Comment by qinqon** [comment]
@rhrazdil this is the result with the fix https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/nmstate_kubernetes-nmstate/1026/pull-kubernetes-nmstate-e2e-handler-k8s/1508393190233739264/artifacts/

**Review by rhrazdil — APPROVED** [review]
Thanks!
/lgtm
/approve

**Comment by rhrazdil** [comment]
/retest

OVS timed out on creating interface:
```
failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1'
libnmstate.error.NmstateDependencyError
  Activate profile uuid:43005db4-7ffb-4564-adac-b28177630fec iface:ovs0 type
    ovs-interface failed
      timeout on creating OVS interface, please check Open vSwitch daemon
```

**Pull request merged**
