### PR TITLE
DNM: Nmstate rust binding

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

The error log from rust are more simple than the pythone ones:
```
message: |-
        error reconciling NodeNetworkConfigurationPolicy at desired state apply: ,
         failed applying nmstate net state {"interfaces":[{"bridge":{"options":{"stp":{"enabled":false}},"port":[{"name":"eth1"}]},"description":"Linux bridge with eth1 as a port","ipv4":{"dhcp":true,"enabled":true},"name":"br1","state":"up","type":"liux-bridge"}]} with rc: 1, err_msg: Failed to find unknown type interface br1 in current state, err_kind: InvalidArgument
```

This PR will remove the error stripping and encoding.

**Special notes for your reviewer**:

Depends on: 
- https://github.com/nmstate/kubernetes-nmstate/pull/969
- https://github.com/nmstate/nmstate/pull/1792
- https://github.com/nmstate/nmstate/pull/1789
- https://github.com/nmstate/nmstate/pull/1794
- https://github.com/nmstate/nmstate/pull/1796
- https://github.com/nmstate/nmstate/pull/1821
- https://github.com/nmstate/nmstate/pull/1830
- https://github.com/nmstate/nmstate/pull/1839
- https://github.com/nmstate/nmstate/pull/1868

TODO:
- Retrieve nmstate version throw nmstate API
- Retrieve host networkmanager version throw nmstate API
- Change nmstate errors formating code
- Add rust support for: 
```yaml
interfaces:
      - ipv4:
          enabled: false
        name: eth1
        state: up
        type: ethernet
      routes:
        config:
        - next-hop-interface: eth1
          state: absent
```

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold
DNM

**Comment by qinqon** [comment]
Looks like the nmstate-rust when the type is unknown report directly the rust type kind of and also add a struct to it
```yaml
    type:
        other: Other("IpTun")
```

**Comment by ffmancera** [comment]
I think this is a bug. It should do what Nmstate currently does when a unknown/unsupported interface is present. We need to fix that, thanks for pointing it out. :)

**Comment by qinqon** [comment]
> I think this is a bug. It should do what Nmstate currently does when a unknown/unsupported interface is present. We need to fix that, thanks for pointing it out. :)

This should do it I think https://github.com/nmstate/nmstate/pull/1821

**Comment by qinqon** [comment]
Is not disabling vlan-filtering when it explicitly disabled 
```
Failure [202.860 seconds]
NodeNetworkState
/tmp/knmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:136
  when desiredState is configured
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:137
    with a linux bridge up with a port with disabled VLAN
    /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:156
      should have the linux bridge at currentState with vlan_filtering 0 and no default vlan range configured [It]
      /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:167

      Timed out after 180.648s.
      Expected
          <string>: 24: br49: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
              link/ether 52:55:00:d1:56:02 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 
              bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 30000 stp_state 0 priority 32768 vlan_filtering 1 vlan_protocol 802.1Q bridge_id 8000.52:55:0:d1:56:2 designated_root 8000.52:55:0:d1:56:2 root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer  112.64 vlan_default_pvid 1 vlan_stats_enabled 0 vlan_stats_per_port 0 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 1 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 16 mcast_hash_max 4096 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3125 mcast_stats_enabled 0 mcast_igmp_version 2 mcast_mld_version 1 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
          
      to contain substring
          <string>: vlan_filtering 0

      /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/simple_bridge_and_bond_test.go:170
```

**Comment by qinqon** [comment]
The route absent works if firt nncp is applied with ipv4: false and then the route is stated as absent, this was working fine with python version.

**Comment by qinqon** [comment]
New failing tests:

74 Passed | 6 Failed | 3 Pending | 0 Skipped

```
Summarizing 6 Failures:
  [FAIL] EnactmentCondition when applying valid config [It] should go from Progressing to Available
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/nnce_conditions_test.go:58
  [FAIL] NodeNetworkState when desiredState is configured with a active-backup miimon 100 bond interface up [AfterEach] should have the bond interface at currentState
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:169
  [FAIL] TOP-LEVEL [AfterEach] NodeNetworkState when desiredState is configured with the bond interface as linux bridge port should have the bond in the linux bridge as port at currentState
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/main_test.go:131
  [FAIL] [nns] NNS Dependencies [It] should include versions of NNS dependencies
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/nns_dependencies_test.go:42
  [FAIL] Static addresses and routes when desiredState is configured with bridge taking over the static networking of the slave [AfterEach] should have the bridge and the routes created
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:169
  [FAIL] Static addresses and routes when desiredState is configured with static V6 address [BeforeEach] should have the static V6 address
  /tmp/knmstate/kubernetes-nmstate/test/e2e/handler/conditions.go:169
```

**Comment by qinqon** [comment]
/retest
Let's see if https://github.com/nmstate/nmstate/pull/1868 fixes stuff

**Pull request closed without merging**
