### PR TITLE
test: add test for global DNS configuration

### PR DESCRIPTION
**Pull request by mkowalski**
**Is this a BUG FIX or a FEATURE ?**:

/kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cathay4t — COMMENTED** [review]
Not sure related or not. It is known that nmstate will always use global DNS for:

```yaml
---
dns-resolver:
  config:
    server:
    - 2001:4860:4860::8888
    - 8.8.8.8
    - 2606:4700:4700::1111
```

With a rollback triggered by bad config, you may verify whether global DNS is reverted or not. Of course, you need mark it as known to be fail.

**Comment by mkowalski** [comment]
But those servers are good, so they will not trigger the revert. If I read the current code correctly, we want the test to contain hardcoded wrong DNS server, that's why I used 192.168.100.3

**Comment by mkowalski** [comment]
/retest

```
go: downloading golang.org/x/mod v0.4.2
/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/api/resource/amount.go:23:2: unrecognized import path "gopkg.in/inf.v0": reading https://gopkg.in/inf.v0?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: timeout
/home/prow/go/pkg/mod/sigs.k8s.io/structured-merge-diff/v4@v4.1.2/value/value.go:26:2: unrecognized import path "gopkg.in/yaml.v2": reading https://gopkg.in/yaml.v2?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: timeout
/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.8.0/pkg/schemapatcher/gen.go:24:2: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: timeout
make: *** [Makefile:134: gen-k8s] Error 1
```

**Comment by mkowalski** [comment]
/hold cancel

That should actually work

**Pull request merged**
