### PR TITLE
run functional tests on std-ci

### PR DESCRIPTION
**Pull request by phoracek**

### CODE REVIEW

**Comment by qinqon** [comment]
ci test please

**Comment by qinqon** [comment]
ci test please

**Comment by phoracek** [comment]
@qinqon this won't pass until we rebase it on your bridge pr

**Comment by cathay4t** [comment]
ci test please

**Comment by qinqon** [comment]
@phoracek was just testing that I can trigger CI from here

**Comment by qinqon** [comment]
ci test please

**Pull request merged**
