### PR TITLE
Brad as maintainer

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:

/kind enhancement

**What this PR does / why we need it**:
He has done big PRs and contributions to project and cares for it.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
@qinqon are you trying to smuggle your PR in this?

**Comment by qinqon** [comment]
@phoracek ups...

**Comment by qinqon** [comment]
/cc @bcrochet 
Are you ok with it ?

**Comment by phoracek** [comment]
/lgtm
/approve

Well deserved

**Comment by qinqon** [comment]
/override 
pull-kubernetes-nmstate-unit-test

**Comment by phoracek** [comment]
/override pull-kubernetes-nmstate-e2e-handler-k8s

Why is CI so terrible

**Pull request merged**
