### PR TITLE
Add okd-4.2 lane

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
ci test please

It's Sunday, repositories are failing.

**Comment by phoracek** [comment]
OKD tests are failing with:

```
• Failure in Spec Setup (BeforeEach) [90.175 seconds]
rollback [BeforeEach]
/tmp/kubernetes-nmstate/go/path/src/github.com/nmstate/kubernetes-nmstate/test/e2e/rollback_test.go:35
  when connectivity to default gw is lost after state configuration
  /tmp/kubernetes-nmstate/go/path/src/github.com/nmstate/kubernetes-nmstate/test/e2e/rollback_test.go:66
    should rollback to a good gw configuration
    /tmp/kubernetes-nmstate/go/path/src/github.com/nmstate/kubernetes-nmstate/test/e2e/rollback_test.go:82
    Unexpected error:
        <*errors.errorString | 0xc0000bf920>: {
           s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred
    /tmp/kubernetes-nmstate/go/path/src/github.com/nmstate/kubernetes-nmstate/test/e2e/utils.go:114
------------------------------
EnactmentCondition when applying valid config 
  should go from Progressing to Available
  /tmp/kubernetes-nmstate/go/path/src/github.com/nmstate/kubernetes-nmstate/test/e2e/nnce_conditions_test.go:40
STEP: Initialize cluster resources
error in opening stream: the server could not find the requested resource
error in opening stream: the server could not find the requested resource
error in opening stream: the server could not find the requested resource
error in opening stream: the server could not find the requested resource
```

Have we forgot to update RBAC with the enactment object?

**Comment by qinqon** [comment]
@phoracek have to be something related to operator-sdk e2e/tests and kubevirtci provider since cluster-sync works fine:
```
++ kubevirtci/cluster-up//kubectl.sh get daemonset -n nmstate nmstate-handler '-o=jsonpath={.status.desiredNumberScheduled}'
+ desiredNumberScheduled=2
++ kubevirtci/cluster-up//kubectl.sh get daemonset -n nmstate nmstate-handler '-o=jsonpath={.status.numberAvailable}'
+ numberAvailable=2
+ '[' 2 == 2 ']'
+ echo 'nmstate-handler DS is ready'
nmstate-handler DS is ready

```

**Comment by qinqon** [comment]
wrong remote

**Pull request closed without merging**
