### PR TITLE
Okd 4.2

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Comment by qinqon** [comment]
ci test please

**Comment by qinqon** [comment]
The error is related to metrics server
```
 metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts   {"error": "error listening on 0.0.0.0:8383: listen tcp 0.0.0.0:8383: bind: address already in use"}
github.com/go-logr/zapr.(*zapLogger).Error
        kubernetes-nmstate/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/metrics.NewListener
        kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go:44
sigs.k8s.io/controller-runtime/pkg/manager.New
        kubernetes-nmstate/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:259
main.main
        kubernetes-nmstate/cmd/manager/main.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:200
2019-12-10T16:24:36.438Z        ERROR   cmd             {"error": "error listening on 0.0.0.0:8383: listen tcp 0.0.0.0:8383: bind: address already in use"}
github.com/go-logr/zapr.(*zapLogger).Error
        kubernetes-nmstate/vendor/github.com/go-logr/zapr/zapr.go:128
main.main
        kubernetes-nmstate/cmd/manager/main.go:99
runtime.main
        /usr/local/go/src/runtime/proc.go:200
```

**Comment by phoracek** [comment]
I would vote to kill metrics and reintroduce them once we have a use-case and tests. Now it is just a dead code for me.

**Comment by qinqon** [comment]
We can just change the port, so we have the code generated by operator-sdk.

**Comment by phoracek** [comment]
@qinqon maybe prow will give us better performance...

**Comment by qinqon** [comment]
ci test please

**Pull request closed without merging**
