### PR TITLE
Add Affinity to NMstate CR

### PR DESCRIPTION
**Pull request by rhrazdil**
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What this PR does / why we need it**:
This PR adds Affinity and InfraAffinity fields to NMState CR, which allows to apply PlacementConfiguration
in full extent.

Depends on:
- https://github.com/nmstate/kubernetes-nmstate/pull/1004

**Special notes for your reviewer**:

**Release note**:

```release-note
Add affinity and infraAffinity fields to NMState
```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold
Depends on https://github.com/nmstate/kubernetes-nmstate/pull/1004

**Comment by rhrazdil** [comment]
/hold cancel
#1004 was merged

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by rhrazdil** [comment]
arm build failed
/test pull-kubernetes-nmstate-e2e-operator-k8s

**Pull request merged**
