### PR TITLE
docker: Remove buildx init/install

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
The buildx version provided with latest docker is more than enough to has the features needed by the project. This change remove the install and initialization to reduce complexity and versions missalignments.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by phoracek — APPROVED** [review]

**Comment by qinqon** [comment]
/override pull-kubernetes-nmstate-e2e-handler-k8s

not related.

**Pull request merged**
