### PR TITLE
Update to golang 1.17

### PR DESCRIPTION
**Pull request by creydr**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What this PR does / why we need it**:
Update to golang 1.17

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
@creydr can you rebase on top of https://github.com/nmstate/kubernetes-nmstate/pull/965 ?

**Comment by creydr** [comment]
> @creydr can you rebase on top of #965 ?

done

**Comment by creydr** [comment]
@qinqon after #965 got merged, I rebased this PR on main branch again

**Pull request merged**
