### PR TITLE
WIP Add script to collect debug information

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:
It is not much, but better than nothing for collecting debug info.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phoracek** [comment]
/hold

I want to add more docs and try it out.

**Comment by qinqon** [comment]
I am adapting the kubevirt k8s reporter, to get stuff, let's have it next week.

**Comment by phoracek** [comment]
But that would be only for tests, right? This script is meant for users to be executed on their clusters before reporting an issue.

**Comment by qinqon** [comment]
It will retrieve stuff between test so you can do per test forensics.

But you right, we need both.

**Pull request closed without merging**
