### PR TITLE
Remove installing nm 1.22 kubevircti already provides it

### PR DESCRIPTION
**Pull request by qinqon**
**Is this a BUG FIX or a FEATURE ?**:
The k8s-1.19 kubevirtci provider has bump nm to 1.22 so kubernetes-nmstate
does not need to install it anymore.

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
what about < k8s-1.19 ?
btw does 1.19 have 1.22 or 1.26?
asking because when i install using those snippet manually i saw it updates to 1.26
is it ok if its 1.26 ?

**Comment by qinqon** [comment]
@oshoval we are aligned with nmstate 0.2 and that's NM 1.22 with current centos8 we can even install 1.26 but we have to be super carefull here, about k8s 1.19 this is the current target version at kubevirt (although is wip there)

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
