### PR TITLE
go: Bump to 1.20

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:

Bump go to 1.20

```release-note
go1.20
```

### CODE REVIEW

**Comment by mkowalski** [comment]
/retest
/lgtm

This makes sense, I will happily start using more recent go

**Comment by cybertron** [comment]
/approve

Typing is hard. :-)

**Comment by qinqon** [comment]
Something is broken at nmstate, future lane is failing at doing an ovs-bridge with with an "state: ignore" (unamanaged) interface

**Pull request merged**
