### PR TITLE
Added owner reference for nns to node

### LINKED ISSUE #13: remove NodeNetworkState after Node removal
when node is deleted, the CRD should be removed as well

### PR DESCRIPTION
**Pull request by HlinaCZ**
Resolves #13

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by HlinaCZ** [comment]
Oh, no. Sorry I forgot to delete the import.

**Comment by SchSeba** [comment]
> Tested manually. (We can add a test removing Nodes, but we don't know how to add them back)

@phoracek I think the best solution for this is to create another lane in the STD-CI with just one test (ginkgo focus) to remove the node.

**Comment by phoracek** [comment]
@SchSeba it looks like there was an issue with the lock before and we just randomly fixed it here by running `dep ensure`.

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
@SchSeba let's do the test :) thanks for not letting me to be lazy

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
ci test please

**Comment by phoracek** [comment]
ci test please

**Pull request merged**
