### PR TITLE
Release 0.47 fix dockerfile openshift

### PR DESCRIPTION
**Pull request by rhrazdil**
Cherry-pick of https://github.com/nmstate/kubernetes-nmstate/pull/817

**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:
Should only be merged if https://github.com/nmstate/kubernetes-nmstate/pull/820 is accepted

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rhrazdil** [comment]
#820 got merged, unholding
/unhold

**Review by phoracek — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
